#!/usr/bin/env bash
#
# Build a native headless dedicated server, without autotools.
#
# The tree's normal build needs autoconf/automake/libtool. This compiles the
# same sources directly with g++ and DEDICATED defined, reusing the source list
# from build.sh, so a relay host can stand up a server to point at with nothing
# but a compiler and libxml2.
#
#   webbuild/build-dedicated.sh [outdir]      # default: webbuild/dedicated
#
# The output directory holds the binary plus the data and var trees the server
# reads at runtime, so it can be copied somewhere and run in place.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$(cd "$HERE/../src" && pwd)"
OUT="${1:-$HERE/dedicated}"

mkdir -p "$OUT"
OUT="$(cd "$OUT" && pwd)"

TOOLS="tArray tCallback tColor tConfiguration tConsole tCrypt tDirectories \
  tError tEventQueue tHeap tLinkedList tLocale tMemStack tRing tSafePTR \
  tString tSysTime tToDo tException tRecorder tRecorderInternal tCommandLine \
  tRandom tMemManager tResourceManager"
NETWORK="md5 nAuthentication nConfig nKrawall nKrawallPrivate nNetObject \
  nNetwork nObserver nPriorizing nServerInfo nSocket nSpamProtection"
ENGINE="eAdvWall eAuthentication eAxis eCamera eDebugLine eDisplay eFloor \
  eGameObject eGrid eKrawall eNetGameObject ePath ePlayer eRectangle eSensor \
  eSound eTeam eTimer eVoter eWall eLagCompensation eChat"
RENDER="rConsole rConsoleGraph rFont rGL rGLRender rModel rRender rDisplayList \
  rScreen rSysdep rTexture rViewport"
TRON="gAIBase gAICharacter gArena gArmagetron gCamera gCycle gCycleMovement \
  gExplosion gFloor gGame gHud gLanguageMenu gLogo gMenus gParser gParticles \
  gSensor gServerBrowser gSparks gSpawn gStuff gTeam gWall gWinZone gFriends \
  gServerFavorites"
UI="uInput uInputQueue uMenu"
# opengl.cpp is omitted: it needs GL headers, and a dedicated server draws
# nothing. Every other file guards its rendering behind DEDICATED itself.
PARTICLES="action_api actions system"

SOURCES=()
for f in $TOOLS;     do SOURCES+=("$SRC/tools/$f.cpp"); done
for f in $NETWORK;   do SOURCES+=("$SRC/network/$f.cpp"); done
for f in $ENGINE;    do SOURCES+=("$SRC/engine/$f.cpp"); done
for f in $RENDER;    do SOURCES+=("$SRC/render/$f.cpp"); done
for f in $TRON;      do SOURCES+=("$SRC/tron/$f.cpp"); done
for f in $UI;        do SOURCES+=("$SRC/ui/$f.cpp"); done
for f in $PARTICLES; do SOURCES+=("$SRC/thirdparty/particles/$f.cpp"); done

# Runtime tree. Paths are compiled in, so the data has to sit where config.h
# says it does; staging it here keeps the build relocatable as a directory.
mkdir -p "$OUT/var/config" "$OUT/var/var" "$OUT/var/resource" "$OUT/var/screenshots"
rm -rf "$OUT/data"
cp -R "$HERE/data" "$OUT/data"

cat > "$OUT/config.h" <<EOF
// Generated by build-dedicated.sh -- paths are baked in, so regenerate if the
// output directory moves.
#ifndef ARMAGETRON_CONFIG_H_DEDI
#define ARMAGETRON_CONFIG_H_DEDI

#define STDC_HEADERS 1
#define HAVE_UNISTD_H 1
#define HAVE_STDLIB_H 1

#define DEDICATED 1
// The custom memory manager's malloc/free macro poisoning collides with modern
// libc++ headers; the system allocator is fine.
#define DONTUSEMEMMANAGER 1

#define HAVE_LIBZ 1
#define HAVE_LIBM 1
#define HAVE_SINF 1
#define HAVE_COSF 1
#define HAVE_TANF 1
#define HAVE_ATAN2F 1
#define HAVE_SQRTF 1
#define HAVE_LOGF 1
#define HAVE_EXPF 1
#define HAVE_FABSF 1
#define HAVE_FLOORF 1
#define HAVE_WMEMSET 1
#define HAVE_SELECT 1
#define HAVE_ISBLANK 1
#define HAVE_SOCKLEN_T 1

#define DATA_DIR             "$OUT/data"
#define CONFIG_DIR           "$OUT/data/config"
#define RESOURCE_DIR         "$OUT/data/resource"
#define INCLUDEDRESOURCE_DIR "$OUT/data/resource/included"
#define AA_DATADIR           "$OUT/data"
#define AA_SYSCONFDIR        "$OUT/data/config"
#define USER_DATA_DIR        "$OUT/var"
#define USER_CONFIG_DIR      "$OUT/var/config"
#define VAR_DIR              "$OUT/var/var"
#define AUTORESOURCE_DIR     "$OUT/var/resource"
#define SCREENSHOT_DIR       "$OUT/var/screenshots"

#define PROGNAME "armagetronad-dedicated"
#define VERSION "0.2.9-dedicated"

#endif
EOF

if [[ ! -f "$OUT/var/config/settings_custom.cfg" ]]; then
  cat > "$OUT/var/config/settings_custom.cfg" <<'EOF'
SERVER_NAME Wasmagetron
SERVER_PORT 4534
MAX_CLIENTS 16
# The browser platform has its own directory; do not advertise upstream.
TALK_TO_MASTER 0
NUM_AIS 1
EOF
fi

echo "Compiling ${#SOURCES[@]} translation units (dedicated)..."
g++ -std=c++17 -O2 -DHAVE_CONFIG_H -DDEDICATED=1 \
  -Wno-narrowing -Wno-deprecated -Wno-register -fno-strict-aliasing -fpermissive -w \
  -I"$OUT" \
  -iquote "$SRC" -iquote "$SRC/tools" -iquote "$SRC/network" -iquote "$SRC/engine" \
  -iquote "$SRC/render" -iquote "$SRC/tron" -iquote "$SRC/ui" \
  -iquote "$SRC/thirdparty/particles" -iquote "$SRC/thirdparty/binreloc" \
  $(pkg-config --cflags libxml-2.0) \
  "${SOURCES[@]}" "$SRC/thirdparty/binreloc/prefix.c" \
  $(pkg-config --libs libxml-2.0) -lz -lm \
  -o "$OUT/armagetronad-dedicated"

echo "Built: $OUT/armagetronad-dedicated"
echo "Run it from $OUT; it listens on UDP 4534 by default."
